In [1]:
import pandas as pd
df = pd.read_csv('data/insurance.csv')

In [ ]:
df.info()
df.describe()

In [4]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
mean = df['charges'].mean()
std = df['charges'].std()
cv = std/mean
print(cv)

0.9125565859727446

In [19]:
q1 = df['age'].quantile(0.25)
q3 = df['age'].quantile(0.75)
iqr = q3 - q1
print(iqr)

24.0

In [20]:
upper_boundary = q3+(1.5*iqr)
lower_boundary = q1-(1.5*iqr)
print(upper_boundary)
print(lower_boundary)

87.0
-9.0

In [ ]:
df['charges'].plot(kind='box')

In [ ]:
df['smoker'].value_counts()

In [26]:
df[df['charges'] > 34489.3][['charges', 'age', 'bmi', 'smoker']]

          charges  age     bmi smoker
14    39611.75770   27  42.130    yes
19    36837.46700   30  35.300    yes
23    37701.87680   34  31.920    yes
29    38711.00000   31  36.300    yes
30    35585.57600   22  35.600    yes
...           ...  ...     ...    ...
1300  62592.87309   45  30.360    yes
1301  46718.16325   62  30.875    yes
1303  37829.72420   43  27.800    yes
1313  36397.57600   19  34.700    yes
1323  43896.37630   42  40.370    yes

[139 rows x 4 columns]

In [28]:
df[(df['charges'] > 34489.3) & (df['smoker'] == 'no')]

      age     sex    bmi  children smoker     region      charges
242    55  female  26.80         1     no  southwest  35160.13457
1012   61  female  33.33         4     no  southeast  36580.28216
1206   59  female  34.80         2     no  southwest  36910.60803

In [ ]:
df['smoker'] = df['smoker'].map({'no':0,'yes':1})
df['sex'] = df['sex'].map({'female':0,'male':1})
df = pd.get_dummies(df,columns=['region'],drop_first=True)

:

In [ ]:
df.corr(numeric_only=True)['charges'].sort_values(ascending=False)

In [ ]:
df.info()

In [34]:
X = df.drop(['charges'],axis=1)
y = df['charges']

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [36]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(X_train_scaled,y_train)
lr_predictions = lr_model.predict(X_test_scaled)

print('Linear Regression')
print("MAE:", mean_absolute_error(y_test, lr_predictions))
print("MSE:", mean_squared_error(y_test, lr_predictions))
print("R²:", r2_score(y_test, lr_predictions))

Linear Regression
MAE: 4181.1944737536505
MSE: 33596915.851361476
R²: 0.7835929767120722

In [37]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

# Random Forest
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train_scaled, y_train)
rf_predictions = rf_model.predict(X_test_scaled)
print("RF - MAE:", mean_absolute_error(y_test, rf_predictions))
print("RF - R²:", r2_score(y_test, rf_predictions))

RF - MAE: 2539.320509051435
RF - R²: 0.8656801355666366

In [39]:
#Decision Tree
dt_model = DecisionTreeRegressor(max_depth=4)
dt_model.fit(X_train_scaled,y_train)
dt_predictions = dt_model.predict(X_test_scaled)
print("DT - MAE:", mean_absolute_error(y_test, dt_predictions))
print("DT - R²:", r2_score(y_test, dt_predictions))

DT - MAE: 2697.765430538481
DT - R²: 0.8641310379678356

In [40]:
# SVR
svr_model = SVR()
svr_model.fit(X_train_scaled, y_train)
svr_predictions = svr_model.predict(X_test_scaled)
print("SVR - MAE:", mean_absolute_error(y_test, svr_predictions))
print("SVR - R²:", r2_score(y_test, svr_predictions))

SVR - MAE: 8612.408423351833
SVR - R²: -0.07008155372454805

In [41]:
# XGBoost
xgb_model = XGBRegressor(random_state=42)
xgb_model.fit(X_train_scaled, y_train)
xgb_predictions = xgb_model.predict(X_test_scaled)
print("XGB - MAE:", mean_absolute_error(y_test, xgb_predictions))
print("XGB - R²:", r2_score(y_test, xgb_predictions))

XGB - MAE: 2648.9472928894074
XGB - R²: 0.8520216431774448

In [43]:
from sklearn.neighbors import KNeighborsRegressor

knr_model = KNeighborsRegressor()
knr_model.fit(X_train_scaled,y_train)
knr_predictions = knr_model.predict(X_test_scaled)

print("KNR - MAE:", mean_absolute_error(y_test, knr_predictions))
print("KNR - R²:", r2_score(y_test, knr_predictions))

KNR - MAE: 3494.746057742537
KNR - R²: 0.8037995832203448

In [44]:
import joblib
joblib.dump(rf_model,'insurance_random_forest_model.pkl')
joblib.dump(scaler,'insurance_scaler.pkl')

['insurance_scaler.pkl']